import { mkdir } from 'fs/promises';
import { CONFIG } from '../config/index.js';
import type { StorageData, Post, Channel } from '../types/index.js';

const DEFAULT_CHANNEL: Channel = {
  id: 'default',
  name: '默认频道',
  description: 'AI Briefing - Daily news summaries generated by AI.',
  theme: 'spring',
  language: 'zh-CN',
  createdAt: new Date(),
  updatedAt: new Date(),
};

/**
 * 确保 data 目录存在
 */
async function ensureDataDir(): Promise<void> {
  try {
    await mkdir(CONFIG.storage.dataDir, { recursive: true });
  } catch (error) {
    console.error('Failed to create data directory:', error);
  }
}

/**
 * 读取完整数据
 */
export async function readStorageData(): Promise<StorageData> {
  try {
    const file = Bun.file(CONFIG.storage.dataFile);
    const exists = await file.exists();

    if (!exists) {
      // 初始化默认数据
      const initialData: StorageData = {
        posts: [],
        channels: {
          [DEFAULT_CHANNEL.id]: DEFAULT_CHANNEL,
        },
      };
      await writeStorageData(initialData);
      return initialData;
    }

    const data = await file.json();

    // 转换日期字段
    data.posts = data.posts.map((post: Post) => ({
      ...post,
      pubDate: new Date(post.pubDate)
    }));

    Object.values(data.channels).forEach((channel: any) => {
      channel.createdAt = new Date(channel.createdAt);
      channel.updatedAt = new Date(channel.updatedAt);
    });

    return data;
  } catch (error) {
    console.error('Failed to read storage data:', error);
    return {
      posts: [],
      channels: {
        [DEFAULT_CHANNEL.id]: DEFAULT_CHANNEL,
      },
    };
  }
}

/**
 * 写入完整数据
 */
export async function writeStorageData(data: StorageData): Promise<void> {
  await ensureDataDir();
  await Bun.write(CONFIG.storage.dataFile, JSON.stringify(data, null, 2));
}

/**
 * 按频道读取文章
 */
export async function readPosts(channel: string): Promise<Post[]> {
  const data = await readStorageData();
  return data.posts.filter(post => post.channel === channel);
}

/**
 * 读取所有文章
 */
export async function readAllPosts(): Promise<Post[]> {
  const data = await readStorageData();
  return data.posts;
}

/**
 * 添加文章（必须指定频道）
 */
export async function addPost(post: Post, channel: string): Promise<void> {
  const data = await readStorageData();

  // 获取频道配置
  const channelConfig = data.channels[channel];
  if (!channelConfig) {
    throw new Error(`Channel "${channel}" not found`);
  }

  // 设置频道字段
  post.channel = channel;

  // 获取该频道的现有文章
  const channelPosts = data.posts.filter((p: Post) => p.channel === channel);

  // 根据频道配置决定保留多少篇文章
  const maxPosts = channelConfig.maxPosts || CONFIG.storage.maxPosts;

  // 重新组织文章：新文章 + 该频道的旧文章 + 其他频道的文章
  const otherChannelPosts = data.posts.filter((p: Post) => p.channel !== channel);
  const updatedChannelPosts = [post, ...channelPosts].slice(0, maxPosts);
  data.posts = [...updatedChannelPosts, ...otherChannelPosts];

  await writeStorageData(data);
}

/**
 * 读取主题配置
 */
export async function readThemes(): Promise<Record<string, any>> {
  try {
    const file = Bun.file(CONFIG.storage.themesFile);
    const exists = await file.exists();
    if (!exists) return {};

    return await file.json();
  } catch (error) {
    console.error('Failed to read themes:', error);
    return {};
  }
}

/**
 * 读取频道配置
 */
export async function readChannel(channelId: string): Promise<Channel | null> {
  const data = await readStorageData();
  return data.channels[channelId] || null;
}

/**
 * 读取所有频道
 */
export async function readAllChannels(): Promise<Record<string, Channel>> {
  const data = await readStorageData();
  return data.channels;
}

/**
 * 创建频道
 */
export async function createChannel(channel: Channel): Promise<void> {
  const data = await readStorageData();

  if (data.channels[channel.id]) {
    throw new Error(`Channel "${channel.id}" already exists`);
  }

  channel.createdAt = new Date();
  channel.updatedAt = new Date();

  data.channels[channel.id] = channel;
  await writeStorageData(data);
}

/**
 * 更新频道
 */
export async function updateChannel(channelId: string, updates: Partial<Channel>): Promise<void> {
  const data = await readStorageData();

  if (!data.channels[channelId]) {
    throw new Error(`Channel "${channelId}" not found`);
  }

  data.channels[channelId] = {
    ...data.channels[channelId],
    ...updates,
    id: channelId,  // 防止修改 ID
    updatedAt: new Date(),
  };

  await writeStorageData(data);
}

/**
 * 删除频道
 */
export async function deleteChannel(channelId: string): Promise<void> {
  if (channelId === 'default') {
    throw new Error('Cannot delete default channel');
  }

  const data = await readStorageData();

  if (!data.channels[channelId]) {
    throw new Error(`Channel "${channelId}" not found`);
  }

  // 删除频道配置
  delete data.channels[channelId];

  // 删除该频道的文章
  data.posts = data.posts.filter((post: Post) => post.channel !== channelId);

  await writeStorageData(data);
}
