import type { Post, Channel } from './index.js';

export interface StorageData {
  posts: Post[];
  channels: Record<string, Channel>;
}

export const DEFAULT_CHANNEL: Channel = {
  id: 'default',
  name: '默认频道',
  description: 'AI Briefing - Daily news summaries generated by AI.',
  theme: 'spring',
  language: 'zh-CN',
  createdAt: new Date(),
  updatedAt: new Date(),
};
