import { join } from 'path';

// 服务配置
export const CONFIG = {
  // 端口配置
  port: Number(process.env.PORT) || 8765,

  // 鉴权配置
  authToken: process.env.AUTH_TOKEN || '',

  // RSS Feed 配置
  feed: {
    title: process.env.FEED_TITLE || 'AI Briefing',
    description: process.env.FEED_DESCRIPTION || 'Daily news summaries generated by AI.',
    url: process.env.FEED_URL || `http://localhost:${Number(process.env.PORT) || 8765}`,
    language: 'zh-CN',
  },

  // 数据存储配置
  storage: {
    dataDir: join(process.cwd(), 'data'),
    dataFile: join(process.cwd(), 'data/data.json'),  // 新的统一数据文件
    postsFile: join(process.cwd(), 'data/posts.json'),  // 保留以兼容
    themesFile: join(process.cwd(), 'themes.json'),
    maxPosts: 100,
  },

  // 内容配置
  content: {
    defaultTheme: 'spring',
    defaultSummaryLength: 150,
  },

  // Channel 配置
  channels: {
    defaultChannel: process.env.DEFAULT_CHANNEL || 'default',
  },
} as const;
