import { Elysia, t } from 'elysia';
import { Feed } from 'feed';
import MarkdownIt from 'markdown-it';
import { randomUUID } from 'crypto';
import { mkdir } from 'fs/promises';
import { join } from 'path';
import { networkInterfaces } from 'os';

// 环境变量配置
const PORT = process.env.PORT || 8765;
const AUTH_TOKEN = process.env.AUTH_TOKEN || '';
const FEED_TITLE = process.env.FEED_TITLE || 'AI Briefing';
const FEED_DESCRIPTION = process.env.FEED_DESCRIPTION || 'Daily news summaries generated by AI.';
const FEED_URL = process.env.FEED_URL || `http://localhost:${PORT}`;

// 数据文件路径
const DATA_DIR = join(process.cwd(), 'data');
const POSTS_FILE = join(DATA_DIR, 'posts.json');

// Markdown 解析器
const md = new MarkdownIt();

// 数据模型
interface Post {
  id: string;
  title: string;
  link: string;
  content: string;
  contentMarkdown: string;
  summary: string;
  tags?: string[];
  author?: string;
  pubDate: Date;
}

// 工具函数

/**
 * 确保 data 目录存在
 */
async function ensureDataDir(): Promise<void> {
  try {
    await mkdir(DATA_DIR, { recursive: true });
  } catch (error) {
    console.error('Failed to create data directory:', error);
  }
}

/**
 * 读取 posts 数据
 */
async function readPosts(): Promise<Post[]> {
  try {
    const file = Bun.file(POSTS_FILE);
    const exists = await file.exists();

    if (!exists) {
      return [];
    }

    const data = await file.json();
    // 将日期字符串转换回 Date 对象
    return data.map((post: any) => ({
      ...post,
      pubDate: new Date(post.pubDate)
    }));
  } catch (error) {
    console.error('Failed to read posts:', error);
    return [];
  }
}

/**
 * 写入 posts 数据
 */
async function writePosts(posts: Post[]): Promise<void> {
  await ensureDataDir();
  await Bun.write(POSTS_FILE, JSON.stringify(posts, null, 2));
}

/**
 * 生成 UUID
 */
function generateId(): string {
  return randomUUID();
}

/**
 * Markdown 转 HTML
 */
function markdownToHtml(markdown: string): string {
  return md.render(markdown);
}

/**
 * 生成纯文本摘要
 */
function generateSummary(html: string, maxLength: number = 150): string {
  // 去除 HTML 标签
  const text = html.replace(/<[^>]*>/g, '');
  // 去除多余空白
  const cleaned = text.replace(/\s+/g, ' ').trim();
  // 截取指定长度
  if (cleaned.length <= maxLength) {
    return cleaned;
  }
  return cleaned.substring(0, maxLength) + '...';
}

// 创建 Elysia 应用
const app = new Elysia()
  .get('/', () => ({
    message: 'Agent2RSS Service',
    version: '1.0.0',
    endpoints: {
      webhook: 'POST /api/webhook',
      rss: 'GET /rss.xml'
    }
  }))

  // POST /api/webhook - 接收 AI Agent 发送的内容
  .post('/api/webhook', async ({ body, headers, set }) => {
    try {
      // 鉴权检查
      const authToken = headers['x-auth-token'];
      if (!authToken || authToken !== AUTH_TOKEN) {
        set.status = 401;
        return { error: 'Unauthorized' };
      }

      // 转换 Markdown 为 HTML
      const html = markdownToHtml(body.content);

      // 生成摘要
      const summary = generateSummary(html);

      // 创建新 Post
      const newPost: Post = {
        id: generateId(),
        title: body.title,
        link: body.link,
        content: html,
        contentMarkdown: body.content,
        summary,
        tags: body.tags,
        author: body.author,
        pubDate: new Date()
      };

      // 读取现有 posts
      const posts = await readPosts();

      // 添加新 post 到开头，保留最新 100 条
      const updatedPosts = [newPost, ...posts].slice(0, 100);

      // 写回文件
      await writePosts(updatedPosts);

      return {
        success: true,
        message: 'Post added successfully',
        post: {
          id: newPost.id,
          title: newPost.title,
          pubDate: newPost.pubDate
        }
      };
    } catch (error) {
      console.error('Error processing webhook:', error);
      set.status = 500;
      return { error: 'Internal server error' };
    }
  }, {
    body: t.Object({
      title: t.String(),
      link: t.String(),
      content: t.String(),
      tags: t.Optional(t.Array(t.String())),
      author: t.Optional(t.String())
    })
  })

  // GET /rss.xml - 生成 RSS feed
  .get('/rss.xml', async ({ set }) => {
    try {
      // 读取 posts
      const posts = await readPosts();

      // 创建 Feed 实例
      const feed = new Feed({
        title: FEED_TITLE,
        description: FEED_DESCRIPTION,
        id: FEED_URL,
        link: FEED_URL,
        language: 'zh-CN',
        feedLinks: {
          rss: `${FEED_URL}/rss.xml`
        },
        copyright: `All rights reserved ${new Date().getFullYear()}`,
        updated: posts.length > 0 ? posts[0].pubDate : new Date()
      });

      // 添加每个 post 到 feed
      for (const post of posts) {
        feed.addItem({
          title: post.title,
          id: post.link,
          link: post.link,
          description: post.summary,
          content: post.content,
          date: post.pubDate,
          author: post.author ? [{ name: post.author }] : undefined,
          category: post.tags?.map(tag => ({ name: tag }))
        });
      }

      // 生成 RSS 2.0 XML
      const rssXml = feed.rss2();

      // 设置响应头
      set.headers['Content-Type'] = 'application/xml; charset=utf-8';

      return rssXml;
    } catch (error) {
      console.error('Error generating RSS:', error);
      set.status = 500;
      return { error: 'Failed to generate RSS feed' };
    }
  })

  .listen(Number(PORT));

// 获取本机局域网 IP
function getLocalIP(): string | null {
  const nets = networkInterfaces();
  for (const name of Object.keys(nets)) {
    const netInfo = nets[name];
    if (!netInfo) continue;
    for (const net of netInfo) {
      // 跳过内部地址和非 IPv4 地址
      if (net.family === 'IPv4' && !net.internal) {
        return net.address;
      }
    }
  }
  return null;
}

const localIP = getLocalIP();

console.log(`🚀 Agent2RSS is running on port ${PORT}`);
console.log(`\n📰 RSS Feed URLs:`);
console.log(`   Local:  http://localhost:${PORT}/rss.xml`);
if (localIP) {
  console.log(`   LAN:    http://${localIP}:${PORT}/rss.xml`);
}
console.log(`\n📡 Webhook endpoint:`);
console.log(`   POST http://localhost:${PORT}/api/webhook`);
