import { Elysia, t } from 'elysia';
import { Feed } from 'feed';
import MarkdownIt from 'markdown-it';
import { randomUUID } from 'crypto';
import { mkdir } from 'fs/promises';
import { join } from 'path';
import { networkInterfaces } from 'os';
import MarkdownItAttrs from 'markdown-it-attrs';
import MarkdownItHighlight from 'markdown-it-highlightjs';
import MarkdownItMark from 'markdown-it-mark';
import MarkdownItSub from 'markdown-it-sub';
import MarkdownItSup from 'markdown-it-sup';
import MarkdownItIns from 'markdown-it-ins';
import MarkdownItAbbr from 'markdown-it-abbr';
import MarkdownItFootnote from 'markdown-it-footnote';
import MarkdownItDeflist from 'markdown-it-deflist';
import { full as markdownItEmoji } from 'markdown-it-emoji';

// ============== 常量配置 ==============
const PORT = process.env.PORT || 8765;
const AUTH_TOKEN = process.env.AUTH_TOKEN || '';
const FEED_TITLE = process.env.FEED_TITLE || 'AI Briefing';
const FEED_DESCRIPTION = process.env.FEED_DESCRIPTION || 'Daily news summaries generated by AI.';
const FEED_URL = process.env.FEED_URL || `http://localhost:${PORT}`;

const DATA_DIR = join(process.cwd(), 'data');
const POSTS_FILE = join(DATA_DIR, 'posts.json');
const THEMES_FILE = join(process.cwd(), 'themes.json');

const MAX_POSTS = 100;
const DEFAULT_SUMMARY_LENGTH = 150;
const DEFAULT_THEME = 'spring';

// ============== 主题系统 ==============

interface Theme {
  name: string;
  description: string;
  styles: Record<string, string>;
}

let themes: Record<string, Theme> = {};

async function loadThemes() {
  try {
    const file = Bun.file(THEMES_FILE);
    const exists = await file.exists();
    if (exists) {
      const loadedThemes = await file.json();
      themes = { ...themes, ...loadedThemes };
    }

    if (Object.keys(themes).length === 0) {
      console.warn('⚠️  未找到主题，使用默认主题');
      themes = { github: getDefaultTheme() };
    }

    console.log(`✅ 已加载 ${Object.keys(themes).length} 个主题:`, Object.keys(themes).join(', '));
  } catch (error) {
    console.error('❌ 加载主题失败:', error);
    themes = { github: getDefaultTheme() };
  }
}

function getDefaultTheme(): Theme {
  return {
    name: 'GitHub',
    description: 'GitHub 官方风格',
    styles: {
      pre: 'background:#f6f8fa;padding:16px;border-radius:6px;margin:16px 0',
      codeInline: 'background:#f6f8fa;padding:2px 6px;border-radius:3px;font-family:monospace;font-size:14px;color:#e83e8c',
      table: 'border-collapse:collapse;margin:16px 0',
      thead: 'background:#f6f8fa',
      th: 'padding:12px;text-align:left;font-weight:600',
      td: 'padding:12px',
      tr: '',
      blockquote: 'border-left:4px solid #0969da;margin:16px 0;padding:8px 16px;color:#57606a',
      h1: 'font-size:32px;font-weight:700;margin:24px 0 16px;line-height:1.25;color:#1f2328',
      h2: 'font-size:24px;font-weight:600;margin:24px 0 16px;line-height:1.25;color:#1f2328',
      h3: 'font-size:20px;font-weight:600;margin:16px 0 12px;line-height:1.25;color:#1f2328',
      h4: 'font-size:16px;font-weight:600;margin:16px 0 12px;line-height:1.25;color:#1f2328',
      h5: 'font-size:14px;font-weight:600;margin:16px 0 12px;line-height:1.25;color:#1f2328',
      h6: 'font-size:13px;font-weight:600;margin:16px 0 12px;line-height:1.25;color:#57606a',
      p: 'margin:16px 0;line-height:1.6;color:#24292f',
      ul: 'margin:16px 0;padding-left:32px',
      ol: 'margin:16px 0;padding-left:32px',
      li: 'margin:4px 0;line-height:1.6',
      a: 'color:#0969da;text-decoration:none',
      hr: 'border:0;border-top:1px solid #d0d7de;margin:24px 0',
      mark: 'background:#fff8c5;padding:2px 4px',
      ins: 'text-decoration:underline;background:#d4f8d4',
      del: 'text-decoration:line-through;color:#82071e;background:#ffebe9',
      img: 'border-radius:6px;margin:16px 0'
    }
  };
}

// ============== Markdown 解析器 ==============

const md = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: true,
  breaks: true
})
  .use(MarkdownItAttrs)
  .use(MarkdownItHighlight)
  .use(MarkdownItMark)
  .use(MarkdownItSub)
  .use(MarkdownItSup)
  .use(MarkdownItIns)
  .use(MarkdownItAbbr)
  .use(MarkdownItFootnote)
  .use(MarkdownItDeflist)
  .use(markdownItEmoji);

// ============== 数据模型 ==============
interface Post {
  id: string;
  title: string;
  link: string;
  content: string;
  contentMarkdown: string;
  summary: string;
  tags?: string[];
  author?: string;
  pubDate: Date;
}

// ============== 工具函数 ==============
async function ensureDataDir(): Promise<void> {
  try {
    await mkdir(DATA_DIR, { recursive: true });
  } catch (error) {
    console.error('Failed to create data directory:', error);
  }
}

async function readPosts(): Promise<Post[]> {
  try {
    const file = Bun.file(POSTS_FILE);
    const exists = await file.exists();
    if (!exists) return [];

    const data = await file.json();
    return data.map((post: any) => ({
      ...post,
      pubDate: new Date(post.pubDate)
    }));
  } catch (error) {
    console.error('Failed to read posts:', error);
    return [];
  }
}

async function writePosts(posts: Post[]): Promise<void> {
  await ensureDataDir();
  await Bun.write(POSTS_FILE, JSON.stringify(posts, null, 2));
}

function generateId(): string {
  return randomUUID();
}

// ============== 样式处理 ==============
function cleanStyle(style: string): string {
  return style
    .replace(/overflow:\s*hidden;?/gi, '')
    .replace(/position:\s*relative;?/gi, '')
    .replace(/transition:[^;]+;?/gi, '')
    .replace(/animation:[^;]+;?/gi, '')
    .replace(/-webkit-animation:[^;]+;?/gi, '');
}

function addInlineStyles(html: string, themeName: string = DEFAULT_THEME): string {
  const theme = themes[themeName]?.styles || themes.github?.styles || getDefaultTheme().styles;

  return html
    // 代码块
    .replace(/<pre>/g, `<pre style="${cleanStyle(theme.pre || '')};max-width:100%;overflow-x:auto">`)
    .replace(/<code class="language-/g, `<code style="font-family:'SF Mono',Monaco,'Cascadia Code','Roboto Mono',Consolas,'Courier New',monospace;font-size:14px;line-height:1.5" class="language-`)
    .replace(/<code>/g, `<code style="${cleanStyle(theme.codeInline || '')}">`)

    // 表格
    .replace(/<table>/g, `<table style="${cleanStyle(theme.table || '')};width:100%;max-width:100%;table-layout:auto">`)
    .replace(/<thead>/g, `<thead style="${cleanStyle(theme.thead || '')}">`)
    .replace(/<th>/g, `<th style="${cleanStyle(theme.th || '')}">`)
    .replace(/<td>/g, `<td style="${cleanStyle(theme.td || '')}">`)
    .replace(/<tr>/g, `<tr style="${cleanStyle(theme.tr || '')}">`)

    // 引用块
    .replace(/<blockquote>/g, `<blockquote style="${cleanStyle(theme.blockquote || '')};max-width:100%">`)

    // 标题
    .replace(/<h1>/g, `<h1 style="${cleanStyle(theme.h1 || '')};max-width:100%">`)
    .replace(/<h2>/g, `<h2 style="${cleanStyle(theme.h2 || '')};max-width:100%">`)
    .replace(/<h3>/g, `<h3 style="${cleanStyle(theme.h3 || '')};max-width:100%">`)
    .replace(/<h4>/g, `<h4 style="${cleanStyle(theme.h4 || '')};max-width:100%">`)
    .replace(/<h5>/g, `<h5 style="${cleanStyle(theme.h5 || '')};max-width:100%">`)
    .replace(/<h6>/g, `<h6 style="${cleanStyle(theme.h6 || '')};max-width:100%">`)

    // 段落和列表
    .replace(/<p>/g, `<p style="${cleanStyle(theme.p || '')};max-width:100%;word-wrap:break-word">`)
    .replace(/<ul>/g, `<ul style="${cleanStyle(theme.ul || '')}">`)
    .replace(/<ol>/g, `<ol style="${cleanStyle(theme.ol || '')}">`)
    .replace(/<li>/g, `<li style="${cleanStyle(theme.li || '')}">`)

    // 其他元素
    .replace(/<a /g, `<a style="${cleanStyle(theme.a || '')}" `)
    .replace(/<hr>/g, `<hr style="${cleanStyle(theme.hr || '')};max-width:100%">`)
    .replace(/<mark>/g, `<mark style="${cleanStyle(theme.mark || '')}">`)
    .replace(/<ins>/g, `<ins style="${cleanStyle(theme.ins || '')}">`)
    .replace(/<del>/g, `<del style="${cleanStyle(theme.del || '')}">`)
    .replace(/<img /g, `<img style="${cleanStyle(theme.img || '')};max-width:100%;height:auto" `);
}

function markdownToHtml(markdown: string, theme: string = DEFAULT_THEME): string {
  const html = md.render(markdown);
  return addInlineStyles(html, theme);
}

function generateSummary(html: string, maxLength: number = DEFAULT_SUMMARY_LENGTH): string {
  const text = html.replace(/<[^>]*>/g, '');
  const cleaned = text.replace(/\s+/g, ' ').trim();
  if (cleaned.length <= maxLength) {
    return cleaned;
  }
  return cleaned.substring(0, maxLength) + '...';
}

// ============== HTTP 服务 ==============

const app = new Elysia()
  .get('/', () => ({
    message: 'Agent2RSS Service',
    version: '1.0.0',
    endpoints: {
      webhook: 'POST /api/webhook',
      rss: 'GET /rss.xml'
    }
  }))

  .post('/api/webhook', async ({ body, headers, set }) => {
    try {
      const authToken = headers['x-auth-token'];
      if (!authToken || authToken !== AUTH_TOKEN) {
        set.status = 401;
        return { error: 'Unauthorized' };
      }

      const contentType = body.contentType || 'markdown';
      const theme = body.theme || DEFAULT_THEME;
      const html = contentType === 'html'
        ? body.content
        : markdownToHtml(body.content, theme);

      const summary = body.description || generateSummary(html);

      const newPost: Post = {
        id: generateId(),
        title: body.title,
        link: body.link,
        content: html,
        contentMarkdown: body.content,
        summary,
        tags: body.tags,
        author: body.author,
        pubDate: new Date()
      };

      const posts = await readPosts();
      const updatedPosts = [newPost, ...posts].slice(0, MAX_POSTS);
      await writePosts(updatedPosts);

      return {
        success: true,
        message: 'Post added successfully',
        post: {
          id: newPost.id,
          title: newPost.title,
          pubDate: newPost.pubDate
        }
      };
    } catch (error) {
      console.error('Error processing webhook:', error);
      set.status = 500;
      return { error: 'Internal server error' };
    }
  }, {
    body: t.Object({
      title: t.String(),
      link: t.String(),
      content: t.String(),
      contentType: t.Optional(t.Union([t.Literal('markdown'), t.Literal('html')])),
      theme: t.Optional(t.String()),
      description: t.Optional(t.String()),
      tags: t.Optional(t.Array(t.String())),
      author: t.Optional(t.String())
    })
  })

  .get('/rss.xml', async ({ set }) => {
    try {
      const posts = await readPosts();

      const feed = new Feed({
        title: FEED_TITLE,
        description: FEED_DESCRIPTION,
        id: FEED_URL,
        link: FEED_URL,
        language: 'zh-CN',
        feedLinks: {
          rss: `${FEED_URL}/rss.xml`
        },
        copyright: `All rights reserved ${new Date().getFullYear()}`,
        updated: posts.length > 0 ? posts[0].pubDate : new Date()
      });

      for (const post of posts) {
        feed.addItem({
          title: post.title,
          id: post.id,
          link: post.link,
          description: post.summary,
          content: post.content,
          date: post.pubDate,
          author: post.author ? [{ name: post.author }] : undefined,
          category: post.tags?.map(tag => ({ name: tag }))
        });
      }

      set.headers['Content-Type'] = 'application/xml; charset=utf-8';
      return feed.rss2();
    } catch (error) {
      console.error('Error generating RSS:', error);
      set.status = 500;
      return { error: 'Failed to generate RSS feed' };
    }
  })

  .listen(Number(PORT));

// ============== 启动 ==============
await loadThemes();

function getLocalIP(): string | null {
  const nets = networkInterfaces();
  for (const name of Object.keys(nets)) {
    const netInfo = nets[name];
    if (!netInfo) continue;
    for (const net of netInfo) {
      if (net.family === 'IPv4' && !net.internal) {
        return net.address;
      }
    }
  }
  return null;
}

const localIP = getLocalIP();

console.log(`🚀 Agent2RSS is running on port ${PORT}`);
console.log(`\n📰 RSS Feed URLs:`);
console.log(`   Local:  http://localhost:${PORT}/rss.xml`);
if (localIP) {
  console.log(`   LAN:    http://${localIP}:${PORT}/rss.xml`);
}
console.log(`\n📡 Webhook endpoint:`);
console.log(`   POST http://localhost:${PORT}/api/webhook`);
